id: A77719724
title: Prayer to Yeshe Tsogyal
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:04:04.675341
  last_modified_at: 2022-03-01 02:04:04.675344
