id: A77719724
title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:04:04.676492
  last_modified_at: 2022-03-01 02:04:04.676495
