id: A77719724
title: A Prayer to Lady Yeshe Tsogyal, the Mother
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:04:04.671502
  last_modified_at: 2022-03-01 02:04:04.671507
