id: A77719724
title: A Prayer to Khandro Yeshé Tsogyal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:04:04.668281
  last_modified_at: 2022-03-01 02:04:04.668287
